name: Build Tweak
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 将 scheme 从 rootless 改为 roothide，以适配 Roothide 越狱
      - uses: theos/build-action@v2
        with:
          scheme: roothide
          sdk: 17.0
          
      - uses: actions/upload-artifact@v4
        with:
          name: com.yourname.autoonlinewallpaper # 建议加上 artifact 名称
          path: packages/*.deb
