name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theos/build-action@v2
        with:
          scheme: rootless
          sdk: 17.0
      - uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
